name: .NET CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Сборка и тестирование
    runs-on: ubuntu-latest

    steps:
      - name: Загружаем код
        uses: actions/checkout@v4

      - name: Устанавливаем .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Восстанавливаем пакеты
        run: dotnet restore

      - name: Собираем проект
        run: dotnet build --no-restore --configuration Release

      - name: Запускаем тесты
        run: dotnet test --no-build --verbosity normal
